# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(db_index=True)),
                ('feed_url', models.URLField(null=True)),
                ('working', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
